import {spawn} from 'node:child_process';
import {mkdir,writeFile,readFile,chmod} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
import net from 'node:net';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const runRoot=resolve(root,'tests','results',new Date().toISOString().replaceAll(':','-'));
await mkdir(runRoot,{recursive:true});
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const containerMode=process.env.LAB_TEST_MODE==='container';
function execute(command,args,options={}){return new Promise((resolve,reject)=>{const c=spawn(command,args,{windowsHide:true,stdio:['ignore','pipe','pipe'],...options});let out='';c.stdout.on('data',x=>out+=x);c.stderr.on('data',x=>out+=x);c.on('error',reject);c.on('exit',code=>code===0?resolve(out):reject(new Error(`${command} exit ${code}: ${out}`)));});}
let total=0;const reports=[];
async function port(){const s=net.createServer();await new Promise(r=>s.listen(0,'127.0.0.1',r));const p=s.address().port;await new Promise(r=>s.close(r));return p;}
async function testRuntime(runtime){
  const p=await port(), base=`http://127.0.0.1:${p}`,data=resolve(runRoot,runtime);await mkdir(data,{recursive:true});
  if(containerMode)await chmod(data,0o777);
  let child,logs='',containerName,attempt=0;
  async function writeJournal(content){
    const journalPath=resolve(data,'events.json');
    if(!containerMode||process.platform==='win32'){await writeFile(journalPath,content);return;}
    const image=process.env[runtime==='csharp'?'CSHARP_IMAGE':'JAVA_IMAGE']||`atlas-${runtime}:local`;
    await new Promise((resolve,reject)=>{const writer=spawn('docker',['run','--rm','-i','--user','0','--mount',`type=bind,source=${data},target=/data`,'--entrypoint','sh',image,'-c','cat > /data/events.json'],{stdio:['pipe','ignore','pipe']});let error='';writer.stderr.on('data',x=>error+=x);writer.on('error',reject);writer.on('exit',code=>code===0?resolve():reject(new Error(error)));writer.stdin.end(content);});
  }
  function execution(portOverride=p,duplicate=false){
    if(containerMode){const image=process.env[runtime==='csharp'?'CSHARP_IMAGE':'JAVA_IMAGE']||`atlas-${runtime}:local`;const name=`atlas-test-${runtime}-${process.pid}-${++attempt}`;if(!duplicate)containerName=name;return ['docker',['run','--rm','--name',name,'--publish',`127.0.0.1:${portOverride}:8080`,'--mount',`type=bind,source=${data},target=/data`,'--read-only','--cap-drop=ALL','--security-opt=no-new-privileges','--tmpfs','/tmp:size=64m,mode=1777',image]];}
    return [runtime==='csharp'?(process.env.LAB_DOTNET||'dotnet'):'java',runtime==='csharp'?[resolve(root,'csharp/bin/Debug/net10.0/SystemDesignLab.dll')]:['-jar',resolve(root,'java/target/system-design-lab-1.0.0.jar')]];
  }
  const start=()=>{const [command,args]=execution();child=spawn(command,args,{cwd:root,env:{...process.env,LAB_ROOT:root,LAB_DATA:data,LAB_PORT:String(p)},windowsHide:true,stdio:['ignore','pipe','pipe']});child.stdout.on('data',x=>logs+=x);child.stderr.on('data',x=>logs+=x);};
  async function ready(){const deadline=Date.now()+120000;while(Date.now()<deadline){if(child.exitCode!==null)throw new Error('Server exited: '+logs);try{const r=await fetch(base+'/health',{signal:AbortSignal.timeout(2000)});if(r.ok)return;}catch{}await delay(100);}throw new Error('Startup timeout: '+logs);}
  async function stop(){if(child.exitCode!==null)return;const ended=new Promise(r=>child.once('exit',r));if(containerMode)await execute('docker',['stop','--time','5',containerName]);else child.kill();await ended;}
  async function req(route,body,status=200){const response=await fetch(base+route,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();assert.equal(response.status,status,`${route}: ${JSON.stringify(result)}`);return result;}
  const checks=[];
  async function check(name,fn){await fn();checks.push(name);total++;console.log(`PASS ${runtime}: ${name}`);}
  try {
    start();await ready();
    let link,ride;
    await check('seven cases start with empty projections',async()=>{const state=await req('/api/state');assert.equal(state.eventCount,0);assert.equal(state.products[0].stock,5);assert.equal((await req('/health')).implementation,runtime);});
    await check('static UI and assets are served',async()=>{for(const path of ['/','/style.css','/app.js']){const r=await fetch(base+path);assert.equal(r.status,200);assert.ok((await r.text()).length>100);}});
    await check('URL validation, redirect and cache hits',async()=>{await req('/api/links',{url:'javascript:alert(1)'},422);link=await req('/api/links',{url:'https://example.com/path?q=1'});for(let i=0;i<2;i++){const r=await fetch(base+'/r/'+link.id,{redirect:'manual'});assert.equal(r.status,302);assert.equal(r.headers.get('location'),link.url);}const s=await req('/api/state');assert.equal(s.cacheHits,1);assert.equal(s.cacheMisses,1);});
    await check('chat rooms and plain text survive projection',async()=>{await req('/api/messages',{room:'general',user:'ana',text:'<script>alert(1)</script>'});await req('/api/messages',{room:'dev',user:'lucas',text:'hola'});const s=await req('/api/state');assert.equal(s.messages.length,2);assert.equal(s.messages[0].room,'general');});
    await check('idempotent orders reject changed payload',async()=>{const body={key:'retry',product:'keyboard',quantity:2};const a=await req('/api/orders',body),b=await req('/api/orders',body);assert.equal(a.id,b.id);assert.equal(a.totalCents,13000);await req('/api/orders',{...body,quantity:1},409);});
    await check('twenty concurrent buyers cannot oversell five units',async()=>{const results=await Promise.all(Array.from({length:20},(_,i)=>fetch(base+'/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:'buyer-'+i,product:'book',quantity:1})})));assert.equal(results.filter(r=>r.status===200).length,5);assert.equal(results.filter(r=>r.status===409).length,15);const s=await req('/api/state');assert.equal(s.products.find(x=>x.id==='book').stock,0);});
    await check('social feed includes followed and own authors only',async()=>{await req('/api/posts',{user:'ana',text:'own'});await req('/api/posts',{user:'lucas',text:'followed'});await req('/api/posts',{user:'other',text:'excluded'});await req('/api/follows',{user:'ana',target:'lucas'});await req('/api/follows',{user:'ana',target:'lucas'});const feed=await req('/api/feed/ana');assert.deepEqual(feed.map(x=>x.text),['followed','own']);await req('/api/posts',{user:'ana',text:'x'.repeat(281)},422);await req('/api/follows',{user:'ana',target:'ana'},422);});
    await check('taxi selects nearest and keeps busy driver unavailable',async()=>{await req('/api/drivers',{id:'near',lat:-2.17,lon:-79.92});await req('/api/drivers',{id:'far',lat:0,lon:0});ride=await req('/api/rides',{user:'ana',lat:-2.17,lon:-79.92});assert.equal(ride.driver,'near');await req('/api/drivers',{id:'near',lat:-2.171,lon:-79.921});assert.equal((await req('/api/state')).drivers.find(x=>x.id==='near').available,false);const second=await req('/api/rides',{user:'lucas',lat:0,lon:0});assert.equal(second.driver,'far');await req('/api/rides',{user:'other',lat:0,lon:0},409);const a=await req('/api/rides/'+ride.id+'/complete',{});const count=(await req('/api/state')).eventCount;const b=await req('/api/rides/'+ride.id+'/complete',{});assert.equal(a.id,b.id);assert.equal((await req('/api/state')).eventCount,count);});
    await check('concurrent taxi requests reserve driver once',async()=>{const results=await Promise.all(Array.from({length:10},(_,i)=>fetch(base+'/api/rides',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({user:'rider-'+i,lat:0,lon:0})})));assert.equal(results.filter(r=>r.status===200).length,1);assert.equal(results.filter(r=>r.status===409).length,9);});
    await check('crawler queue completes cycles without duplicate visits',async()=>{const job=await req('/api/crawl',{root:'a',pages:{a:['b','c'],b:['a','c'],c:['missing']}});let done;for(let i=0;i<40;i++){done=(await req('/api/state')).jobs.find(x=>x.id===job.id);if(done.status==='completed')break;await delay(100);}assert.equal(done.status,'completed');assert.deepEqual(done.visited,['a','b','c']);await req('/api/crawl',{root:'bad',pages:{a:[]}},422);});
    await check('file versions, owner checks and optimistic concurrency',async()=>{const body={id:'notes',user:'ana',name:'notes.txt',content:Buffer.from('version one').toString('base64'),expectedVersion:0};const a=await req('/api/files',body);assert.equal(a.version,1);assert.equal(a.bytes,11);assert.equal(a.sha256.length,64);await req('/api/files',{...body,user:'other',expectedVersion:1},403);const results=await Promise.all([1,2].map(i=>fetch(base+'/api/files',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,expectedVersion:1,content:Buffer.from('v2-'+i).toString('base64')})})));assert.equal(results.filter(r=>r.status===200).length,1);assert.equal(results.filter(r=>r.status===409).length,1);assert.equal((await req('/api/files/notes?version=1')).content,body.content);assert.equal((await req('/api/files/notes')).version,2);await req('/api/files',{...body,id:'big',content:Buffer.alloc(65537).toString('base64')},422);});
    await check('malformed input returns client errors',async()=>{let r=await fetch(base+'/api/posts',{method:'POST',body:'{broken'});assert.equal(r.status,400);r=await fetch(base+'/api/posts',{method:'POST',body:'[]'});assert.equal(r.status,400);await req('/api/orders',{key:'invalid',product:'book',quantity:1.5},422);await req('/api/drivers',{id:'invalid',lat:91,lon:0},422);await req('/api/missing',{},404);await req('/api/files/no-file',undefined,404);});
    await check('trailing JSON and noncanonical base64 are rejected',async()=>{const r=await fetch(base+'/api/posts',{method:'POST',body:'{"user":"ana","text":"x"} {}'});assert.equal(r.status,400);await req('/api/files',{id:'invalid',user:'ana',name:'x',expectedVersion:0,content:'SG9sYQ'},422);});
    await check('pending crawler jobs recover from journal on startup',async()=>{await stop();const journalPath=resolve(data,'events.json');const events=JSON.parse(await readFile(journalPath,'utf8'));events.push({sequence:events.length+1,time:Date.now(),type:'CrawlQueued',data:{id:'recovered-job',root:'a',pages:{a:['b'],b:['a']},status:'queued'}});await writeJournal(JSON.stringify(events));start();await ready();let done;for(let n=0;n<40;n++){done=(await req('/api/state')).jobs.find(x=>x.id==='recovered-job');if(done.status==='completed')break;await delay(100);}assert.equal(done.status,'completed');assert.deepEqual(done.visited,['a','b']);});
    let saved;
    await check('event history has contiguous sequence',async()=>{const e=await req('/api/events');assert.ok(e.length>15);for(let i=0;i<e.length;i++)assert.equal(e[i].sequence,i+1);saved=await req('/api/state');});
    await check('restart replays every projection and preserves idempotency',async()=>{await stop();start();await ready();const after=await req('/api/state');saved.cacheHits=0;saved.cacheMisses=0;assert.deepEqual(after,saved);const old=saved.orders.find(x=>x.key==='retry');const retried=await req('/api/orders',{key:'retry',product:'keyboard',quantity:2});assert.equal(retried.id,old.id);assert.equal((await req('/api/files/notes?version=1')).version,1);});
    await check('data directory refuses simultaneous writers',async()=>{const duplicatePort=await port();const [command,args]=execution(duplicatePort,true);const duplicate=spawn(command,args,{cwd:root,env:{...process.env,LAB_ROOT:root,LAB_DATA:data,LAB_PORT:String(duplicatePort)},windowsHide:true,stdio:'ignore'});const code=await new Promise((r,j)=>{const t=setTimeout(()=>{duplicate.kill();j(new Error('Second writer was allowed'));},10000);duplicate.on('exit',c=>{clearTimeout(t);r(c);});});assert.notEqual(code,0);});
    await check('event journal on disk is valid JSON',async()=>{const e=JSON.parse(await readFile(resolve(data,'events.json'),'utf8'));assert.equal(e.length,saved.eventCount);});
    await check('corrupt journal fails startup without resetting data',async()=>{await stop();const journalPath=resolve(data,'events.json');const original=await readFile(journalPath,'utf8');await writeJournal('{broken');start();const code=await new Promise((r,j)=>{const t=setTimeout(()=>{child.kill();j(new Error('Corrupt journal was accepted'));},30000);child.on('exit',c=>{clearTimeout(t);r(c);});});assert.notEqual(code,0);assert.equal(await readFile(journalPath,'utf8'),'{broken');await writeJournal(original);});
    reports.push({runtime,passed:checks.length,checks});
  } finally {await stop();await writeFile(resolve(runRoot,runtime+'.log'),logs);}
}
try{await testRuntime('csharp');await testRuntime('java');await writeFile(resolve(runRoot,'report.json'),JSON.stringify({date:new Date().toISOString(),total,reports},null,2));console.log(`\n${total} checks passed. Report: ${runRoot}`);}catch(error){console.error(error);process.exitCode=1;}
